# Generated by Django 3.0.5 on 2020-04-06 07:36

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название Категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Название Категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Отобразить')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Назание')),
                ('description', models.CharField(blank=True, max_length=320, null=True, verbose_name='Описание')),
                ('size', models.CharField(blank=True, max_length=120, null=True, verbose_name='Габариты')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('images', models.ImageField(upload_to=main.models.image_upload_to, verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SubCategory', verbose_name='Категория')),
            ],
        ),
    ]
